builds:
- main: main.go
  binary: hello-world
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - hello-world.license.txt
